import Head from 'next/head';
import { Background, MainTemplateWrapper } from './MainTemplate.styles';
import MainHeader from '../Header/Header';
import MainContent from '../Content/Content';
import MainFooter from '../Footer/Footer';

const MainTemplate = () => {
  return (
    <>
      <MainTemplateWrapper>
        <Background>
          <Head>
            <title>ComPropp</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <MainHeader />
          <MainContent />
          <MainFooter />
        </Background>
      </MainTemplateWrapper>
    </>
  );
};

export default MainTemplate;
